version: '3.8'

services:
  expenseincomeapp:
    build: .
    image: expense-income-app:latest
    container_name: expense-income-app
    depends_on:
      - h2db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2db:1521/mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    entrypoint: ["sh", "-c", "until nc -z -v -w30 h2db 1521; do echo 'Waiting for H2 DB...'; sleep 5; done; java -jar /app/ExpenseIncomeProject.jar"]

  h2db:
    image: oscarfonts/h2:latest
    container_name: h2db
    ports:
      - "1521:1521"
      - "8082:8082"  # H2 Web Console
    environment:
      - H2_OPTIONS=-ifNotExists -tcpAllowOthers -web -webPort 8082 -ifNotExists
    volumes:
      - h2db-data:/opt/h2-data  # Persistent storage for H2

volumes:
  h2db-data:
    driver: local
